feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostView

app_name = 'feed'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('detail/<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('post/', AddPostView.as_view(), name='post'),
]

practice/urls.py
from practice.settings import MEDIA_ROOT
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from feed import urls as feed_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(feed_urls, namespace='feed')),
]

#this is an insecure way to serve static files - need to be turned off and refactored for production
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.
class Post(models.Model):
    text = models.CharField(max_length=255, blank=False, null=False)
    image = ImageField()

    def __str__(self):
        return self.text

feed/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

feed/views.py
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .forms import PostForm
from .models import Post

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Welcome'] = "Hello and Welcome! This is a Website Made with Django"
        context['posts'] = Post.objects.all().order_by('-id')
        return context

class PostDetailView(DetailView):
    template_name = 'detail.html'
    model = Post
    
class AddPostView(FormView):
    template_name = 'new_post.html'
    form_class = PostForm
    success_url = '/' #add a separate html later with home link?

    #creating a method inside the class to make request exist for success message
    #messages need to be enabled in the base.html because it should be in all pages
    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        #creating a new post on the home.html
        new_object = Post.objects.create(
            text=form.cleaned_data['text'],
            image=form.cleaned_data['image']
        )
        messages.add_message(self.request, messages.SUCCESS, 'You have successfully submitted your post!')
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default Title{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if messages.tag %} class="{{ messages.tag }}" {% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block body %}{% endblock %}
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}{{ object.text }}{% endblock%}

{% block body %}
    <a href="{% url 'feed:index' %}">&larr; Go Back</a>
    <h4>Text of the post</h4>
    {{ object.text }}
    <h4>Image of the post</h4>
    <img src="{{ object.image.url }}" style="width: 60%; height: auto;">
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}
homepage
{% endblock %}

{% block body %}
<h1>{{ Welcome }} &#x1f600; &#x1f680;</h1>
<h3>
    <a href="{% url 'feed:post'%}">Add a new post &rarr;</a>
<h3>
<h2>
    {% for post in posts %}
         <a href="{% url 'feed:detail' post.id %}">
         {{ post.text }}
        <br>
        {% thumbnail post.image "250x250" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        </a>
        <hr>
    {% endfor %}
</h2>
{% endblock %}

templates/new_post.html
{% extends "base.html" %}

{% block title %}Upload a new post{% endblock%}

{% block body %}
    <a href="{% url 'feed:index' %}">&larr; Go Back</a>
    <br>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
    <div>
        <button type="submit">Submit post</button>
    </div>
{% endblock %}